/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.curtin.projectfileanalyzer;

public class App {
    public static void main(String[] args) {
        if (args.length > 0)
            System.out.println(args[0]);
        else
            System.out.println("Nothing here");
    }
}
